version: "3.8"

services:
  api:
    build: ./server
    ports:
      - 5000:5000
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq/data:/var/lib/rabbitmq
      - rabbitmq/log:/var/log/rabbitmq
    
  worker:
    build: ./video-worker
    volumes:
      - video-worker:/app
    depends_on:
      - rabbitmq
  
volumes:
  video-worker:
  rabbitmq: