version: "3.8"

services:
  client:
    build: ./client
    ports:
      - 8080:8080

  server:
    build: ./server
    ports:
      - 3000:3000
    depends_on:
      - rabbitmq
    command: >
      sh -c "until curl -s rabbitmq:15672 >/dev/null; do sleep 1; done && npm run start"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq:/var/lib/rabbitmq
      - rabbitmq:/var/log/rabbitmq

  worker:
    build: ./worker
    volumes:
      - worker:/app
    depends_on:
      - rabbitmq
    command: >
      sh -c "until curl -s rabbitmq:15672 >/dev/null; do sleep 1; done && go run ."

volumes:
  worker:
  rabbitmq:
